### ISSUE TITLE
User receives "The user denied permission to use Service Worker" Error

### ISSUE THREAD

**Issue by dan-tr** [microsoft/azure-boards-estimate#47]
We have one user who cannot create a new session. When she clicks on the New Session button she receives the message "Connecting to server" and after that it just spins.

Debugging though the JavaScript console showed a "The user denied permission to use Service Worker" error. Online research showed that error can occur if the user has disallowed third-party cookies, but in this case the user was allowing them. Several other users have been successful. To our knowledge this user in the only person experiencing this issue.

Here is the output from the JavaConsole:

```
registerServiceWorker.ts:90 Error during service worker registration: DOMException: Failed to register a ServiceWorker for scope ('https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/estimate/2.3.1/1628859047668/build/') with script ('https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/estimate/2.3.1/1628859047668/build/service-worker.js'): The user denied permission to use Service Worker.
(anonymous) @ registerServiceWorker.ts:90
extmgmt.dev.azure.com/tr-ihn-sandbox/_apis/ExtensionManagement/InstalledExtensions/ms-devlabs/estimate/Data/Scopes/Default/Current/Collections/sessions/Documents:1 Failed to load resource: the server responded with a status of 404 ()
extmgmt.dev.azure.com/tr-ihn-sandbox/_apis/ExtensionManagement/InstalledExtensions/ms-devlabs/estimate/Data/Scopes/Default/Current/Collections/EstimationSessions/Documents:1 Failed to load resource: the server responded with a status of 404 ()
extmgmt.dev.azure.com/tr-ihn-sandbox/_apis/ExtensionManagement/InstalledExtensions/ms-devlabs/estimate/Data/Scopes/Default/Current/Collections/%24settings/Documents/bc26e72c-fcf6-4f9a-9887-f0d103be2ef1-field-configuration:1 Failed to load resource: the server responded with a status of 404 ()
Utils.js:347 Warning: Error from HTTP request. 0:
e.log @ Utils.js:347
Utils.js:343 Error: Failed to complete negotiation with the server: Error
e.log @ Utils.js:343
Utils.js:343 Error: Failed to start the connection: Error
e.log @ Utils.js:343
signalr.ts:80 Error
(anonymous) @ signalr.ts:80
utils.js:262 uncaught at jr at jr
at p
at Sr
at hr
Error: Cannot send data if the connection is not in the 'Connected' State.
at e.send (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/estimate/2.3.1/1628859047668/build/static/js/1.e6e482ab.chunk.js:1:360750)
at e.send (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/estimate/2.3.1/1628859047668/build/static/js/1.e6e482ab.chunk.js:1:342620)
at https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/estimate/2.3.1/1628859047668/build/static/js/main.65a9252c.chunk.js:1:65400
at x (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/estimate/2.3.1/1628859047668/build/static/js/1.e6e482ab.chunk.js:1:491041)
at Generator._invoke (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/estimate/2.3.1/1628859047668/build/static/js/1.e6e482ab.chunk.js:1:490829)
at Generator.e.<computed> [as next] (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/estimate/2.3.1/1628859047668/build/static/js/1.e6e482ab.chunk.js:1:491220)
at r (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/estimate/2.3.1/1628859047668/build/static/js/1.e6e482ab.chunk.js:1:16673)
at s (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/estimate/2.3.1/1628859047668/build/static/js/1.e6e482ab.chunk.js:1:16875)
at https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/estimate/2.3.1/1628859047668/build/static/js/1.e6e482ab.chunk.js:1:16934
at new Promise (<anonymous>)
O @ utils.js:262
msdevlabs-estimate-backend.azurewebsites.net//estimate/negotiate?sessionId=3gbnq&tfId=0c9d5622-2169-6fda-98b2-304dd7b4846b:1 Failed to load resource: net::ERR_CONNECTION_RESET
DevTools failed to load source map: Could not load content for https://amcdn.msftauth.net/scripts/me/MeControl/10.21162.3/en-US/meBoot.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://amcdn.msftauth.net/scripts/me/MeControl/10.21162.3/en-US/meCore.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://amcdn.msftauth.net/meInlineBackCompat.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Comment by MOlausson** [comment]
@dan-tr thanks for reporting. We'll track this and try to repro using the info you provided.

**Comment by dan-tr** [comment]
User just confirmed that she is no longer encountering this issue. It just started working. She is not sure why.

**Comment by MOlausson** [comment]
@dan-tr thanks for the update. I'll close this issue then and hope it works well from now.
